/**
 * Delete Site Dialog with GitHub-style confirmation.
 *
 * Blocked when the site has deployments. Users must handle
 * deployments (reassign or delete) from the deployments page first.
 */

import { useEffect, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useNavigate, useParams } from "react-router-dom";
import { AlertTriangle } from "lucide-react";
import { sitesApi } from "../../api/sites";
import type { SiteWithStats } from "../../api/types";
import { invalidateProjectData } from "../../lib/invalidate-project";
import { Button } from "../ui/button";
import { Callout } from "../ui/callout";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";
import { Input } from "../ui/input";
import { Label } from "../ui/label";

interface DeleteSiteDialogProps {
  site: SiteWithStats | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DeleteSiteDialog({
  site,
  open,
  onOpenChange,
}: DeleteSiteDialogProps) {
  const queryClient = useQueryClient();
  const navigate = useNavigate();
  const { projectId } = useParams<{ projectId: string }>();
  const [confirmText, setConfirmText] = useState("");

  useEffect(() => {
    if (!open) {
      setConfirmText("");
    }
  }, [open]);

  const deleteMutation = useMutation({
    mutationFn: () => sitesApi.delete(site!.id),
    onSuccess: () => {
      // Site deletion nulls out site_id on any linked deployments and
      // changes site filter options / map overlays. Blanket invalidate.
      if (projectId) {
        invalidateProjectData(queryClient, projectId);
      }
      queryClient.invalidateQueries({ queryKey: ["sites-with-stats", projectId] });
      onOpenChange(false);
    },
    onError: (error: Error) => {
      console.error("Failed to delete site:", error);
    },
  });

  const handleDelete = () => {
    if (site && confirmText === site.name) {
      deleteMutation.mutate();
    }
  };

  const handleGoToDeployments = () => {
    onOpenChange(false);
    navigate(`/projects/${projectId}/deployments`);
  };

  if (!site) return null;

  const hasDeployments = site.deployment_count > 0;
  const isConfirmValid = confirmText === site.name;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-destructive" />
            Delete site
          </DialogTitle>
          <DialogDescription>
            {hasDeployments
              ? "This site cannot be deleted while it has deployments."
              : "This action cannot be undone. This will permanently delete the site."}
          </DialogDescription>
        </DialogHeader>

        {hasDeployments ? (
          <div className="space-y-4">
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
              <p className="text-sm font-medium text-destructive mb-2">
                This site has {site.deployment_count} deployment{site.deployment_count === 1 ? "" : "s"}
              </p>
              <p className="text-sm text-destructive/90">
                To avoid orphaning data, deployments must be handled first. You can
                reassign them to a different site or delete them from the Deployments page.
              </p>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
              <p className="text-sm font-medium text-destructive mb-2">
                Warning - This will permanently delete
              </p>
              <ul className="text-sm text-destructive/90 list-disc list-inside space-y-1">
                <li>The site and all its metadata</li>
                <li>Any tags and custom fields</li>
              </ul>
            </div>

            <Callout variant="info">
              Your original images and videos will not be deleted. Only data
              generated by AddaxAI will be removed.
            </Callout>

            <div className="space-y-2">
              <Label htmlFor="confirm-delete-site">
                Please type{" "}
                <span className="font-mono font-semibold bg-muted px-1.5 py-0.5 rounded">
                  {site.name}
                </span>{" "}
                to confirm
              </Label>
              <Input
                id="confirm-delete-site"
                value={confirmText}
                onChange={(e) => setConfirmText(e.target.value)}
                placeholder={site.name}
                autoComplete="off"
              />
            </div>
          </div>
        )}

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </Button>
          {hasDeployments ? (
            <Button
              type="button"
              onClick={handleGoToDeployments}
            >
              Go to deployments
            </Button>
          ) : (
            <Button
              type="button"
              variant="destructive"
              onClick={handleDelete}
              disabled={!isConfirmValid || deleteMutation.isPending}
            >
              {deleteMutation.isPending ? "Deleting..." : "Delete site"}
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
