#!/usr/bin/env python3
"""
Check that every classification model runs, picks the right compute
device, and still agrees with the legacy AddaxAI.

Run this by hand on each OS after porting models or bumping an
environment. It is deliberately not part of CI: it needs real weights and
real micromamba envs (many GB), which no other test in this repo touches.

What it checks, per model:

  runs      the classification subprocess exits 0 and returns a label
  device    the device the model actually chose, reported by the worker
            itself. Some models are legitimately CPU-only (see
            EXPECTED_CPU), and those are not failures.
  taxonomy  every class the model emits has a row in taxonomy.csv.
            Detection.label is matched against label_taxonomy.name by
            plain string equality with no foreign key, so one typo drops
            a species out of the filter tree and out of rollup with no
            error anywhere. Cheap to check here, invisible in production.
  matches   the whole top-5, not just the winner. For each of the top
            TOP_K classes the label must equal what the expectation
            recorded, in order, with the confidence within
            CONF_TOLERANCE. Comparing the top-1 alone would miss a model
            that still names the right animal but has scrambled the rest
            of its distribution, which is exactly what a broken crop or
            normalisation does. Expectations come from
            tests/data/model_expectations.json (the `top_k` block),
            generated by scripts/generate_legacy_ground_truth.py. Models
            in CONFIDENCE_DIVERGES are checked on the labels only, because
            we deliberately report a different number to legacy; the
            ranking still has to match.

An expectation records where it came from, and the table says so. Most
are `legacy`, meaning the legacy AddaxAI really produced that answer.
A few are `reference`: a model legacy cannot run, or runs so wrongly that
its output is not a baseline. Those expectations are this port's own
first run on macOS, frozen with --record-reference. They cannot tell you
the port was right in the first place, because nothing independent
agreed, but they still do real work: on the machine that recorded them
they match by construction, and on a different OS they turn any drift in
label or confidence into a visible failure. That is the whole point of
running this on Windows and Ubuntu.

Confidence is compared loosely on purpose. Ground truth is generated on
one machine (MPS), and the same weights on CUDA or CPU differ in the last
few decimals. A tight bound would fail on Windows for no reason, so the
labels must match exactly while the confidence only has to be close. And
the comparison stops at the first rank the expectation stored as ~0
(NEGLIGIBLE_CONF): below the ground truth's own five-decimal precision
the ordering is undefined, so two effectively-zero classes trading places
is not counted as a failure.

Usage
-----
    cd backend
    source venv/bin/activate

    python scripts/test_models.py                     # every cls model
    python scripts/test_models.py --model AHDRIFT-v1  # just one
    python scripts/test_models.py --skip-missing      # only what is downloaded
    python scripts/test_models.py --model-dir ./staged/AHDRIFT-v1
    python scripts/test_models.py --model-dir ./staged/X --record-reference

Options:
    --model         Model id. Repeatable. Default: every cls model in the catalog.
    --skip-missing  Skip models whose weights are not downloaded, instead of
                    downloading them (a full run pulls many GB).
    --model-dir     Test a directory directly, bypassing the catalog. Use to
                    validate a staged inference.py before uploading it to
                    HuggingFace.
    --json          Emit machine-readable results instead of the table.
    --record-reference
                    Write this run's own top-5 into the expectations file as a
                    `reference` baseline, for a model legacy cannot run or runs
                    wrongly. Works with --model-dir or against the catalog; in
                    catalog mode it records every model tested that has no
                    legacy baseline and refuses to overwrite one that does. On
                    a fresh OS this is how you seed models like SpeciesNet
                    before you have a Windows/Ubuntu number to trust.

Exit code is 0 when every model tested passed, 1 otherwise.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import sys
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.ml.environment_manager import EnvironmentManager  # noqa: E402
from app.ml.inference.custom_classification_model import (  # noqa: E402
    CustomClassificationModel,
)
from app.ml.label_exclusion import NON_LABEL_CLASSES  # noqa: E402
from app.ml.model_storage import ModelStorage  # noqa: E402
from app.ml.schemas.model_manifest import ModelManifest  # noqa: E402

EXPECTATIONS_PATH = (
    Path(__file__).resolve().parent.parent / "tests" / "data" / "model_expectations.json"
)
# The catalog in this checkout, which is the thing under test. Reading
# the local manifest dirs instead would only ever see models a catalog
# sync has already pulled, so a newly added entry would be silently
# skipped and the run would still say PASS.
CATALOG_PATH = Path(__file__).resolve().parent.parent.parent / "models.json"

# Top-1 confidence may drift this far from the recorded ground truth
# before it is called a failure. Wide enough to absorb MPS/CUDA/CPU
# float differences, tight enough that a wrong preprocessing step (which
# moves confidence by far more than this) still trips it.
CONF_TOLERANCE = 0.02

# How deep the label/confidence comparison goes. The ground truth stores
# five; comparing them catches a scrambled distribution the top-1 would
# hide. The comparison stops early at the first rank the expectation
# recorded as negligible (see below), so this is a ceiling, not a
# guarantee of five real comparisons.
TOP_K = 5

# The comparison stops at the first rank whose expected confidence is
# below this floor: below it a class is not a real prediction, and its
# exact rank is numerical noise between two independent implementations
# (the legacy adapter vs this port, on possibly different devices/
# frameworks). Two classes at ~0.0001 trading places is a coin flip, not
# a regression. This keeps the check on the meaningful head of the
# distribution (a broken crop or normalisation moves real probability
# mass, which shows up there) while ignoring the flip-prone tail. So the
# comparison is deep when the distribution is spread and shallow when the
# model is confident, which is exactly when there is nothing else worth
# checking. 0.1% is well below any actionable camera-trap prediction.
NEGLIGIBLE_CONF = 1e-3

# Models that cannot use the GPU, with the reason. Being on this list
# turns "ran on CPU" from a failure into an expected result.
EXPECTED_CPU: dict[str, str] = {
    # andrea-anpc calls tf.config.set_visible_devices([], 'GPU') on
    # Darwin, so TropiCam-AI is CPU-only on macOS by the model's own
    # choice, not ours.
    "NEO-MNCN-v1-0": "darwin",
    # KIR-HEX-v1's check_gpu only looks at CUDA: "this model architecture
    # is not compatible with MPS (Apple Silicon)". CPU on a Mac is the
    # model's own decision, and it does use the GPU on Windows.
    "KIR-HEX-v1": "darwin",
}

# Models where we deliberately report a different confidence to legacy,
# with the reason. The top-1 label is still checked exactly: a wrong
# label means a broken port either way. Only the number is exempt.
CONFIDENCE_DIVERGES: dict[str, str] = {
    # Multi-label: the head is read with a sigmoid, so the 81 scores are
    # independent and do not sum to 1. Legacy's remove_forbidden_classes
    # divides every score by their sum regardless, which is a no-op for
    # the softmax models but rescales this one by ~1/1.54. We report the
    # model's real probability instead. Scaling is monotonic, so the
    # ranking (and therefore the label) is identical either way.
    "NZS-WEK-v3-03": "multi-label sigmoid; legacy rescales by 1/sum",
}


@dataclass
class TestImage:
    """One shared test image, with the box every model classifies."""

    name: str
    url: str
    sha256: str
    # Normalised MegaDetector box: (x_min, y_min, width, height).
    bbox: tuple[float, float, float, float]


# The fixed, shared image set. Defined here rather than in the
# expectations file so there is one definition of "what we test on";
# generate_legacy_ground_truth.py imports this list, so the ground truth
# and the test can never disagree about which pixels they mean.
#
# Every model sees the same image. This is primarily a fidelity check
# (does the port reproduce its recorded baseline), but a crow is a
# reasonable accuracy check too: almost every model has a "bird" class,
# so a broken crop or normalisation shows up not just as a changed number
# but often as a changed, obviously-wrong label.
#
# Public LILA BC images, served from the project's Google Cloud mirror.
# The box is the dataset's own annotation, not the full frame: a crow
# fills a fraction of the image, so the box exercises each model's crop
# path the way a real MegaDetector detection would.
TEST_IMAGES: list[TestImage] = [
    # American Crow on grass, from the ENA24 dataset (file 7932.jpg). A
    # bird is in-range for almost every model here (nearly all carry a
    # "bird" class), so unlike a regional mammal this image is a sensible
    # sanity check across the whole zoo, not just deterministic nonsense.
    # bbox is ENA24's own American Crow annotation, normalised.
    TestImage(
        name="ena24_american_crow.jpg",
        url=(
            "https://storage.googleapis.com/public-datasets-lila/"
            "ena24/images/7932.jpg"
        ),
        sha256="834bcc11334de7e6e04231049630499bb7ecd5ef7c10eca6144612ccbda6ad9a",
        bbox=(0.3533, 0.5305, 0.2070, 0.1494),
    ),
]


@dataclass
class Result:
    model_id: str
    friendly_name: str = ""
    env: str = ""
    device: str = ""
    top1: str = ""
    expected: str = ""
    delta: float | None = None
    source: str = ""
    status: str = "SKIP"
    predictions: list = field(default_factory=list)
    # Per image, the model's own top-TOP_K as [(label, confidence), ...].
    top5: list = field(default_factory=list)
    notes: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.status in ("PASS", "SKIP")


def _load_expectations() -> dict:
    if not EXPECTATIONS_PATH.exists():
        print(
            f"No expectations file at {EXPECTATIONS_PATH}.\n"
            f"Models will be checked for 'runs' and 'device' only. Generate "
            f"the ground truth with scripts/generate_legacy_ground_truth.py "
            f"to also check outputs against legacy.",
            file=sys.stderr,
        )
        return {}
    with open(EXPECTATIONS_PATH) as f:
        return json.load(f)


def _cache_dir() -> Path:
    path = Path.home() / "AddaxAI" / "test-images"
    path.mkdir(parents=True, exist_ok=True)
    return path


def _fetch_image(image: TestImage) -> Path:
    """Download the image once and verify its hash. Cached across runs."""
    dest = _cache_dir() / image.name
    if dest.exists():
        digest = hashlib.sha256(dest.read_bytes()).hexdigest()
        if digest == image.sha256:
            return dest
        print(f"  cached {image.name} has the wrong hash, refetching")

    print(f"  downloading {image.name}")
    urllib.request.urlretrieve(image.url, dest)
    digest = hashlib.sha256(dest.read_bytes()).hexdigest()
    if digest != image.sha256:
        raise SystemExit(
            f"{image.name} hash mismatch.\n"
            f"  expected {image.sha256}\n"
            f"  got      {digest}\n"
            f"The upstream file changed; ground truth is no longer comparable."
        )
    return dest


def _check_taxonomy_joins(model_dir: Path, class_names: dict[str, str]) -> list[str]:
    """
    Report classes the model emits that taxonomy.csv has no row for.

    Not a failure: taxonomy.csv is optional and a model without one still
    classifies, it just falls back to a flat label list. But a taxonomy
    that is present and *nearly* right is worse than none, because the
    missing species vanish silently.

    Compared case-insensitively, which is what the app does: taxonomy.csv's
    model_class is lowercased into LabelTaxonomy.name, while Detection.label
    keeps the case the model emitted, and the linking matches the two on
    lowercase.
    """
    taxonomy_path = model_dir / "taxonomy.csv"
    if not taxonomy_path.exists():
        return ["no taxonomy.csv (flat label list, no rollup)"]

    with open(taxonomy_path, newline="", encoding="utf-8-sig") as f:
        rows = {(r.get("model_class") or "").strip().lower() for r in csv.DictReader(f)}

    # Non-label classes (false detection, blank, empty, ...) never reach
    # the database: json_pipeline drops a detection whose top-1 is one of
    # them, so they never need a taxonomy row. VIC-ADS-v1 omits
    # `false detection` and is right to.
    emitted = {
        name.strip().lower()
        for name in class_names.values()
        if name.strip().lower() not in NON_LABEL_CLASSES
    }
    unjoined = sorted(emitted - rows)
    if not unjoined:
        return []
    shown = ", ".join(unjoined[:5])
    more = f" (+{len(unjoined) - 5} more)" if len(unjoined) > 5 else ""
    return [f"{len(unjoined)}/{len(emitted)} classes missing from taxonomy.csv: {shown}{more}"]


def run_model(
    model_id: str,
    model_dir: Path,
    model_path: Path,
    env_name: str,
    expectation: dict | None,
    friendly_name: str = "",
) -> Result:
    """Classify the shared image set with one model."""
    result = Result(model_id=model_id, friendly_name=friendly_name, env=env_name)

    items = []
    for image in TEST_IMAGES:
        items.append(
            {
                "source": "image",
                "image_path": str(_fetch_image(image)),
                "bbox": list(image.bbox),
            }
        )

    model = CustomClassificationModel(
        model_dir=model_dir,
        model_path=model_path,
        env_name=env_name,
        env_manager=EnvironmentManager(),
    )
    # batch_size=None lets the worker pick its own default, which is the
    # path a real analysis takes.
    results, class_names, device, _best = model.classify_detections(items)

    result.device = device
    result.notes.extend(_check_taxonomy_joins(model_dir, class_names))
    if device == "CPU":
        reason = EXPECTED_CPU.get(model_id)
        if reason and reason == sys.platform:
            result.notes.append("CPU expected on this OS")
        else:
            result.notes.append("no GPU used")

    predictions = []
    top5_per_image = []
    for item_result in results:
        if item_result is None:
            result.status = "FAIL"
            result.notes.append("returned no classification")
            return result
        ranked = sorted(
            item_result.all_probabilities.items(),
            key=lambda kv: kv[1],
            reverse=True,
        )[:TOP_K]
        top5_per_image.append(ranked)
        predictions.append((item_result.label, item_result.confidence))

    result.top1 = predictions[0][0]
    result.predictions = predictions
    result.top5 = top5_per_image

    if not expectation:
        result.status = "RAN"
        result.notes.append("no ground truth recorded")
        return result

    result.source = expectation.get("source", "legacy")
    diverges = CONFIDENCE_DIVERGES.get(model_id)
    if diverges:
        result.notes.append(f"confidence differs from legacy by design: {diverges}")

    expected_topk = expectation.get("top_k")
    result.status = "PASS"
    for i, our5 in enumerate(top5_per_image):
        # Older ground truth may carry only top-1 (`predictions`); fall
        # back to it so an un-regenerated file still checks the winner.
        want5 = (
            expected_topk[i]
            if expected_topk and i < len(expected_topk)
            else [expectation["predictions"][i]]
        )
        if i == 0:
            result.expected = want5[0]["label"]
            result.delta = abs(our5[0][1] - want5[0]["confidence"])
        depth = min(len(our5), len(want5))
        for rank in range(depth):
            want = want5[rank]
            if want["confidence"] < NEGLIGIBLE_CONF:
                # Sorted descending, so every rank below this is also
                # negligible. Stop before comparing an order the 5dp
                # ground truth cannot actually pin down.
                break
            got_label, got_conf = our5[rank]
            if got_label != want["label"]:
                result.status = "FAIL"
                result.notes.append(
                    f"image {i} rank {rank + 1}: got {got_label!r}, "
                    f"expected {want['label']!r}"
                )
                # Once the ordering diverges, the ranks below it are no
                # longer comparing the same classes. Stop.
                break
            if not diverges and abs(got_conf - want["confidence"]) > CONF_TOLERANCE:
                result.status = "FAIL"
                result.notes.append(
                    f"image {i} rank {rank + 1}: {got_label!r} confidence off by "
                    f"{abs(got_conf - want['confidence']):.4f} "
                    f"(got {got_conf:.4f}, expected {want['confidence']:.4f})"
                )
    return result


def _record_reference(model_id: str, top5_per_image: list) -> None:
    """
    Freeze a run's own output as the expectation for a model legacy
    cannot provide one for. Writes the full top-TOP_K, so the resulting
    baseline is checked at the same depth as a legacy one.

    Marked `reference` rather than `legacy` so the expectations file
    never claims the legacy app said something it did not.
    """
    with open(EXPECTATIONS_PATH) as f:
        data = json.load(f)
    data.setdefault("models", {})[model_id] = {
        "source": "reference",
        "predictions": [
            {"label": img5[0][0], "confidence": img5[0][1]} for img5 in top5_per_image
        ],
        "top_k": [
            [{"label": label, "confidence": conf} for label, conf in img5]
            for img5 in top5_per_image
        ],
    }
    with open(EXPECTATIONS_PATH, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"recorded {model_id} as a `reference` expectation (not legacy)")


# Notes that the columns already say, so printing them too is noise.
_REDUNDANT_NOTES = {"CPU expected on this OS", "no GPU used"}


def _device_cell(r: Result) -> str:
    """GPU / CPU ok / CPU! — the one thing you want to see at a glance."""
    if not r.device:
        return "-"
    if r.device != "CPU":
        return "GPU"
    return "CPU ok" if "CPU expected on this OS" in r.notes else "CPU!"


_NAME_W = 24


def _print_table(results: list[Result]) -> None:
    header = (
        f"{'model':<22} {'name':<{_NAME_W}} {'env':<14} {'device':<8} status"
    )
    print("\n" + header)
    print("-" * len(header))
    for r in results:
        print(
            f"{r.model_id:<22} {r.friendly_name[:_NAME_W]:<{_NAME_W}} "
            f"{r.env:<14} {_device_cell(r):<8} {r.status}"
        )
        for note in r.notes:
            if note not in _REDUNDANT_NOTES:
                print(f"{'':<22} -> {note}")
    print("-" * len(header))
    counts: dict[str, int] = {}
    for r in results:
        counts[r.status] = counts.get(r.status, 0) + 1
    print("  ".join(f"{k}: {v}" for k, v in sorted(counts.items())))
    print(
        "\ndevice: GPU good | CPU ok = this model is CPU-only here by design | "
        "CPU! = unexpected fallback"
    )
    print(
        f"status: PASS = top-{TOP_K} labels and confidences agree with the "
        f"recorded baseline (label only where noted)"
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Check every classification model runs, uses the right "
        "device, and matches legacy AddaxAI output."
    )
    parser.add_argument(
        "--model", action="append", dest="models", help="Model id. Repeatable."
    )
    parser.add_argument(
        "--skip-missing",
        action="store_true",
        help="Skip models whose weights are not downloaded.",
    )
    parser.add_argument(
        "--model-dir",
        help="Test a model directory directly, bypassing the catalog.",
    )
    parser.add_argument("--json", action="store_true", help="Emit JSON.")
    parser.add_argument(
        "--record-reference",
        action="store_true",
        help="Freeze this run's own output as a `reference` expectation.",
    )
    args = parser.parse_args(argv)

    expectations = _load_expectations()

    storage = ModelStorage()
    results: list[Result] = []

    if args.model_dir:
        model_dir = Path(args.model_dir).resolve()
        manifest_path = model_dir / "manifest.json"
        if not manifest_path.exists():
            raise SystemExit(f"No manifest.json in {model_dir}")
        manifest_data = json.loads(manifest_path.read_text())
        results.append(
            run_model(
                model_id=manifest_data["model_id"],
                model_dir=model_dir,
                model_path=model_dir / manifest_data["model_fname"],
                env_name=manifest_data["env"],
                expectation=expectations.get("models", {}).get(
                    manifest_data["model_id"]
                ),
                friendly_name=manifest_data.get("friendly_name", ""),
            )
        )
        if args.record_reference and results[0].top5:
            _record_reference(results[0].model_id, results[0].top5)
        _print_table(results)
        return 0 if all(r.ok for r in results) else 1

    with open(CATALOG_PATH) as f:
        entries = json.load(f)["models"]["cls"]
    manifests = []
    for entry in entries:
        if args.models and entry["model_id"] not in args.models:
            continue
        m = ModelManifest(**entry)
        m.model_category = "classification"
        manifests.append(m)
    if args.models:
        missing = set(args.models) - {m.model_id for m in manifests}
        if missing:
            raise SystemExit(f"Not in {CATALOG_PATH.name}: {', '.join(sorted(missing))}")
    print(f"Testing {len(manifests)} classification model(s) from {CATALOG_PATH}")

    for manifest in sorted(manifests, key=lambda m: m.model_id):
        result = Result(
            model_id=manifest.model_id,
            friendly_name=manifest.friendly_name or "",
            env=manifest.env,
        )
        try:
            if not storage.check_weights_ready(manifest):
                if args.skip_missing:
                    result.notes.append("weights not downloaded")
                    results.append(result)
                    continue
                print(f"Downloading {manifest.model_id}...")
                storage.download_weights(manifest)

            result = run_model(
                model_id=manifest.model_id,
                model_dir=storage.get_model_path(manifest),
                model_path=storage.get_model_file(manifest),
                env_name=manifest.env,
                expectation=expectations.get("models", {}).get(manifest.model_id),
                friendly_name=manifest.friendly_name or "",
            )
        except Exception as e:
            result.status = "ERROR"
            result.notes.append(f"{type(e).__name__}: {e}")
        results.append(result)

    if args.record_reference:
        existing = expectations.get("models", {})
        for r in results:
            if not r.top5:
                continue
            prior = existing.get(r.model_id)
            if prior and prior.get("source") == "legacy":
                print(
                    f"skip {r.model_id}: has a legacy expectation, "
                    f"not overwriting it with a local run"
                )
                continue
            _record_reference(r.model_id, r.top5)

    if args.json:
        print(json.dumps([r.__dict__ for r in results], indent=2, default=str))
    else:
        _print_table(results)
    return 0 if all(r.ok for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
