/**
 * Delete Project Dialog with type-to-confirm.
 */

import { useMutation, useQueryClient } from "@tanstack/react-query";
import { projectsApi, type ProjectResponse } from "../../api/projects";
import { Callout } from "../ui/callout";
import { TypeToConfirmDialog } from "../ui/type-to-confirm-dialog";

interface DeleteProjectDialogProps {
  project: ProjectResponse | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DeleteProjectDialog({
  project,
  open,
  onOpenChange,
}: DeleteProjectDialogProps) {
  const queryClient = useQueryClient();

  const deleteMutation = useMutation({
    mutationFn: () => projectsApi.delete(project!.id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["projects"] });
      onOpenChange(false);
    },
    onError: (error: Error) => {
      console.error("Failed to delete project:", error);
    },
  });

  if (!project) return null;

  return (
    <TypeToConfirmDialog
      open={open}
      onOpenChange={onOpenChange}
      title="Delete project"
      description="This action cannot be undone. This will permanently delete the project and all associated data."
      confirmWord={project.name}
      confirmLabel="Delete project"
      pendingLabel="Deleting..."
      onConfirm={() => deleteMutation.mutate()}
      isPending={deleteMutation.isPending}
      variant="destructive"
    >
      <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
        <p className="text-sm font-medium text-destructive mb-2">
          Warning - This will permanently delete
        </p>
        <ul className="text-sm text-destructive/90 list-disc list-inside space-y-1">
          <li>All sites and deployment information</li>
          <li>All AI predictions and classifications</li>
          <li>All observation results and analyses</li>
          <li>All metadata and database records</li>
        </ul>
      </div>

      <Callout variant="info">
        Your original images and videos will not be deleted. Only data
        generated by AddaxAI will be removed.
      </Callout>
    </TypeToConfirmDialog>
  );
}
