/**
 * Delete Deployment Dialog with type-to-confirm.
 *
 * Mirrors DeleteSiteDialog. Users must type `{site_name} - {start_date}`
 * to confirm. Deletion cascades to files, events, and detections in the
 * database. Files on disk are not touched.
 */

import { useEffect, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle } from "lucide-react";
import { deploymentsApi } from "../../api/deployments";
import { invalidateProjectData } from "../../lib/invalidate-project";
import { Button } from "../ui/button";
import { Callout } from "../ui/callout";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../ui/dialog";
import { Input } from "../ui/input";
import { Label } from "../ui/label";

export interface DeleteDeploymentTarget {
  id: string;
  site_name: string;
  start_date_local: string;
}

interface DeleteDeploymentDialogProps {
  deployment: DeleteDeploymentTarget | null;
  projectId: string;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function DeleteDeploymentDialog({
  deployment,
  projectId,
  open,
  onOpenChange,
}: DeleteDeploymentDialogProps) {
  const queryClient = useQueryClient();
  const [confirmText, setConfirmText] = useState("");

  useEffect(() => {
    if (!open) {
      setConfirmText("");
    }
  }, [open]);

  const deleteMutation = useMutation({
    mutationFn: () => deploymentsApi.delete(deployment!.id),
    onSuccess: () => {
      // Deletion cascades to files, detections, and events. Blanket
      // invalidate so every page reflects the removed data.
      invalidateProjectData(queryClient, projectId);
      queryClient.invalidateQueries({ queryKey: ["sites-with-stats", projectId] });
      onOpenChange(false);
    },
    onError: (error: Error) => {
      console.error("Failed to delete deployment:", error);
    },
  });

  if (!deployment) return null;

  const confirmString = "DELETE";
  const isConfirmValid = confirmText === confirmString;

  const handleDelete = () => {
    if (isConfirmValid) {
      deleteMutation.mutate();
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <AlertTriangle className="h-5 w-5 text-destructive" />
            Delete deployment
          </DialogTitle>
          <DialogDescription>
            This action cannot be undone. This will permanently delete the deployment
            and all associated data.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="text-sm">
            <p className="text-muted-foreground">Deployment</p>
            <p className="font-medium">
              {deployment.site_name} - {deployment.start_date_local}
            </p>
          </div>

          <div className="rounded-lg border border-destructive/50 bg-destructive/10 p-4">
            <p className="text-sm font-medium text-destructive mb-2">
              Warning - This will permanently delete
            </p>
            <ul className="text-sm text-destructive/90 list-disc list-inside space-y-1">
              <li>The deployment and all its metadata</li>
              <li>All file records, observations, and events</li>
              <li>All human verifications on those observations</li>
            </ul>
          </div>

          <Callout variant="info">
            Your original images and videos will not be deleted. Only data
            generated by AddaxAI will be removed.
          </Callout>

          <div className="space-y-2">
            <Label htmlFor="confirm-delete-deployment">
              Please type{" "}
              <span className="font-mono font-semibold bg-muted px-1.5 py-0.5 rounded">
                {confirmString}
              </span>{" "}
              to confirm
            </Label>
            <Input
              id="confirm-delete-deployment"
              value={confirmText}
              onChange={(e) => setConfirmText(e.target.value)}
              placeholder={confirmString}
              autoComplete="off"
            />
          </div>
        </div>

        <DialogFooter>
          <Button
            type="button"
            variant="outline"
            onClick={() => onOpenChange(false)}
          >
            Cancel
          </Button>
          <Button
            type="button"
            variant="destructive"
            onClick={handleDelete}
            disabled={!isConfirmValid || deleteMutation.isPending}
          >
            {deleteMutation.isPending ? "Deleting..." : "Delete deployment"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
