"""add tags to sites and deployments

Revision ID: f4d205e3c4e0
Revises: b2c3d4e5f6a7
Create Date: 2026-04-11 22:48:06.446677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4d205e3c4e0'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('tags', sa.JSON(), nullable=False, server_default='{}'))
    op.add_column('sites', sa.Column('tags', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sites', 'tags')
    op.drop_column('deployments', 'tags')
    # ### end Alembic commands ###
