"""add video and image counts to deployment queue

Revision ID: bc299da8af53
Revises: 328afecc7200
Create Date: 2026-01-14 14:42:38.794045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc299da8af53'
down_revision: Union[str, None] = '328afecc7200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite workaround: Add as nullable first, set defaults, then make NOT NULL
    op.add_column('deployment_queue', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('deployment_queue', sa.Column('image_count', sa.Integer(), nullable=True))

    # Set default values for existing rows
    op.execute('UPDATE deployment_queue SET video_count = 0 WHERE video_count IS NULL')
    op.execute('UPDATE deployment_queue SET image_count = 0 WHERE image_count IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_queue', 'image_count')
    op.drop_column('deployment_queue', 'video_count')
    # ### end Alembic commands ###
