"""initial schema

Revision ID: 94d6210f7c39
Revises: 
Create Date: 2026-01-11 20:00:10.378666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d6210f7c39'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_jobs_created', 'jobs', ['created_at'], unique=False)
    op.create_index('idx_jobs_status', 'jobs', ['status'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('detection_model_id', sa.String(length=100), nullable=False),
    sa.Column('classification_model_id', sa.String(length=100), nullable=True),
    sa.Column('excluded_classes', sa.JSON(), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('state_code', sa.String(length=2), nullable=True),
    sa.Column('detection_threshold', sa.Float(), nullable=False),
    sa.Column('event_smoothing', sa.Boolean(), nullable=False),
    sa.Column('taxonomic_rollup', sa.Boolean(), nullable=False),
    sa.Column('taxonomic_rollup_threshold', sa.Float(), nullable=False),
    sa.Column('independence_interval', sa.Integer(), nullable=False),
    sa.Column('video_fps', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('habitat_type', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_site_name_per_project')
    )
    op.create_table('deployment_queue',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('deployment_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deployments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('folder_path', sa.Text(), nullable=True),
    sa.Column('folder_status', sa.String(length=20), nullable=False),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('camera_model', sa.String(length=255), nullable=True),
    sa.Column('camera_serial', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_deployment', 'events', ['deployment_id'], unique=False)
    op.create_index('idx_events_time', 'events', ['start_time', 'end_time'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('exif_data', sa.JSON(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index('idx_files_deployment', 'files', ['deployment_id'], unique=False)
    op.create_index('idx_files_timestamp', 'files', ['timestamp'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bbox_x', sa.Float(), nullable=False),
    sa.Column('bbox_y', sa.Float(), nullable=False),
    sa.Column('bbox_width', sa.Float(), nullable=False),
    sa.Column('bbox_height', sa.Float(), nullable=False),
    sa.Column('species', sa.String(length=100), nullable=True),
    sa.Column('species_confidence', sa.Float(), nullable=True),
    sa.Column('classification_all_probs', sa.JSON(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_detections_category', 'detections', ['category'], unique=False)
    op.create_index('idx_detections_confidence', 'detections', ['confidence'], unique=False)
    op.create_index('idx_detections_file', 'detections', ['file_id'], unique=False)
    op.create_index('idx_detections_frame_number', 'detections', ['frame_number'], unique=False)
    op.create_index('idx_detections_job', 'detections', ['job_id'], unique=False)
    op.create_index('idx_detections_species', 'detections', ['species'], unique=False)
    op.create_index('idx_detections_species_confidence', 'detections', ['species_confidence'], unique=False)
    op.create_table('event_files',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('file_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'file_id')
    )
    op.create_index('idx_event_files_event', 'event_files', ['event_id'], unique=False)
    op.create_index('idx_event_files_file', 'event_files', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_event_files_file', table_name='event_files')
    op.drop_index('idx_event_files_event', table_name='event_files')
    op.drop_table('event_files')
    op.drop_index('idx_detections_species_confidence', table_name='detections')
    op.drop_index('idx_detections_species', table_name='detections')
    op.drop_index('idx_detections_job', table_name='detections')
    op.drop_index('idx_detections_frame_number', table_name='detections')
    op.drop_index('idx_detections_file', table_name='detections')
    op.drop_index('idx_detections_confidence', table_name='detections')
    op.drop_index('idx_detections_category', table_name='detections')
    op.drop_table('detections')
    op.drop_index('idx_files_timestamp', table_name='files')
    op.drop_index('idx_files_deployment', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_events_time', table_name='events')
    op.drop_index('idx_events_deployment', table_name='events')
    op.drop_table('events')
    op.drop_table('deployments')
    op.drop_table('deployment_queue')
    op.drop_table('sites')
    op.drop_table('projects')
    op.drop_index('idx_jobs_status', table_name='jobs')
    op.drop_index('idx_jobs_created', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('idx_audit_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
