"""Add video support: frame_number to detections, video_fps to projects

Revision ID: 97b59efb067e
Revises: 08c3ad432da3
Create Date: 2026-01-07 14:19:34.857520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97b59efb067e'
down_revision: Union[str, None] = '08c3ad432da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('frame_number', sa.Integer(), nullable=True))
    op.create_index('idx_detections_frame_number', 'detections', ['frame_number'], unique=False)
    op.create_index('idx_detections_species', 'detections', ['species'], unique=False)
    op.create_index('idx_detections_species_confidence', 'detections', ['species_confidence'], unique=False)
    op.add_column('projects', sa.Column('video_fps', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'video_fps')
    op.drop_index('idx_detections_species_confidence', table_name='detections')
    op.drop_index('idx_detections_species', table_name='detections')
    op.drop_index('idx_detections_frame_number', table_name='detections')
    op.drop_column('detections', 'frame_number')
    # ### end Alembic commands ###
