"""add notes and tags to deployment queue

Revision ID: bfd49dc7b370
Revises: f4d205e3c4e0
Create Date: 2026-04-12 15:39:13.812719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfd49dc7b370'
down_revision: Union[str, None] = 'f4d205e3c4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployment_queue', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column(
        'deployment_queue',
        sa.Column('tags', sa.JSON(), nullable=False, server_default='{}'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployment_queue', 'tags')
    op.drop_column('deployment_queue', 'notes')
    # ### end Alembic commands ###
