name: Upload to Azure Storage

on:
  push:
    branches:
      - env-download-runtime
  workflow_dispatch:

jobs:
  upload-to-azure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Set up Azure CLI
    #   uses: azure/setup-azurecli@v1
    #   with:
    #     azure-cliversion: latest

    # - name: Authenticate with Azure
    #   run: |
    #     echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_credentials.json
    #     az login --service-principal -u $(jq -r .clientId azure_credentials.json) -p $(jq -r .clientSecret azure_credentials.json) --tenant $(jq -r .tenantId azure_credentials.json)

    - name: Install Miniconda
      run: |
        mkdir "$HOME/azure_upload" 
        cd "$HOME/azure_upload"
        curl --ipv4 -L "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh" -o miniforge.sh

    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Uploading to Azure storage...
      with:
        connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
        container_name: github-zips-beta
        source_folder: /home/runner/azure_upload
        destination_folder: v5.23
        is_recursive: false
        delete_if_exists: true
        
    - uses: LanceMcCarthy/Action-AzureBlobUpload@v2
      name: Uploading to Azure storage...
      with:
        connection_string: ${{ secrets.AZURE_CONNECTION_STRING }}
        container_name: github-zips-beta
        source_folder: /home/runner/azure_upload
        destination_folder: latest
        is_recursive: false
        delete_if_exists: true    

    # - name: Upload file to Azure Storage
    #   run: |
    #     az storage blob upload --account-name addaxaifilestorage --container-name github-zips --file miniforge.sh --name miniforge.sh --auth-mode key
