name: temp-test

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "What is tag name of the latest release? E.g., v5.29"
        required: true
  release:
    types:
      - published

jobs:
  build-windows-release:
    runs-on: windows-2022

    env:
      RELEASE_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || inputs.tag_name }}
      BUCKET_NAME: github-release-files-storage
      CONDA_DIR: C:\Miniconda
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Upload URL for Release
        id: get_release
        uses: actions/github-script@v6
        with:
          script: |
            const release = await github.rest.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: '${{ env.RELEASE_VERSION }}',
            })
            // Write the upload URL to the environment file instead of using set-output
            const fs = require('fs');
            fs.appendFileSync(process.env.GITHUB_ENV, `UPLOAD_URL=${release.data.upload_url}\n`);

      - name: Create temp.txt file with content
        run: |
          "Hello World!" | Out-File -FilePath "temp.txt"
        shell: powershell

      - name: Remove existing asset if present
        run: |
          $ErrorActionPreference = "Stop"
          
          # List all assets in the release
          $release_info = curl -H "Authorization: token $env:GITHUB_TOKEN" `
            https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/tags/$env:RELEASE_VERSION
      
          # Extract asset ID by matching the name
          $asset = ($release_info | ConvertFrom-Json).assets | Where-Object { $_.name -eq "Windows-installer-$env:RELEASE_VERSION.zip" }
          $asset_id = $asset.id
          Write-Host "asset_id is $asset_id"
      
          # Check if the asset exists and delete it
          if ($asset_id) {
            curl -X DELETE `
              -H "Authorization: token $env:GITHUB_TOKEN" `
              "https://api.github.com/repos/$env:GITHUB_REPOSITORY/releases/assets/$asset_id"
          } else {
            Write-Host "Asset not found. Continue with upload..."
          }
        shell: powershell

      - name: Upload Asset to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}  # Use the updated environment variable
          asset_path: "temp.txt"
          asset_name: "Windows-installer-${{ env.RELEASE_VERSION }}.exe"
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
