name: temp test

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the latest release tag
        id: fetch_tag
        run: |
          latest_tag=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)
          echo "Latest release tag: $latest_tag"
          echo "tag=$latest_tag" >> $GITHUB_ENV

      - name: Use the release tag
        run: |
          echo "Running workflow for release tag: ${{ env.tag }}"
        
