name: test temp

on:
  workflow_dispatch:
    inputs:
      info:
        description: "Manual trigger workflow:       Selecting 'main' uploads to the official Google bucket available to users      (2) Selecting any other branch uploads to the beta-versions bucket"
        required: false
        default: "(dummy input field - no need to fill in)"
  release:
    types:
      - published

jobs:
  test-temp:
    runs-on: macos-15

    env:
      BRANCH_NAME: "${{ github.ref_name }}"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: release_info
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: PetervanLunteren
          repo: EcoAssist

      - name: set vars
        run: |
          RELEASE_VERSION=${{ steps.release_info.outputs.release }}
          echo RELEASE_VERSION: $RELEASE_VERSION
          echo "RELEASE_VERSION=${{ steps.release_info.outputs.release }}" >> $GITHUB_ENV

      - name: Check vars
        run: |
          echo RELEASE_VERSION: $RELEASE_VERSION

      # - name: Print the ref
      #   run: |
      #     echo "Triggered from branch or tag: ${{ github.ref }}"

      # - name: Extract branch name
      #   run: |
      #     echo "Branch: ${GITHUB_REF#refs/heads/}"

      - name: Set environment variable based on branch
        run: |
          if [ "$BRANCH_NAME" = "main" ]; then
            echo "BUCKET_NAME=github-release-files-storage" >> $GITHUB_ENV
          else
            echo "BUCKET_NAME=github-release-files-storage-beta-versions" >> $GITHUB_ENV
          fi
      
      - name: Print the global environment variable
        run: echo "BUCKET_NAME is $BUCKET_NAME"

