name: Sign Installer

on:
  workflow_dispatch:

jobs:
  sign-installer:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up OpenSSL
      run: sudo apt-get install openssl

    - name: Decode private key from secrets
      run: echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem

    - name: Decode certificate from secrets
      run: echo "${{ secrets.CERTIFICATE }}" > certificate.pem

    - name: Sign installer
      run: |
        # Replace with your installer file

        # Download the installer from the given URL
        curl -L -o windows-installer-latest.exe https://storage.googleapis.com/github-release-files-storage/latest/windows-installer-latest.exe
    
        # Sign the installer
        openssl smime -sign -in windows-installer-latest.exe -out windows-installer-latest.signed.exe -signer certificate.pem -inkey private_key.pem -outform DER

        INSTALLER_FILE="your_installer_file.exe"

        # Use openssl to sign the installer
        # openssl smime -sign -in $INSTALLER_FILE -out $INSTALLER_FILE.signed -signer certificate.pem -inkey private_key.pem -outform DER
        # Optionally, you can verify the signed file:
        openssl smime -verify -inform DER -in $INSTALLER_FILE.signed -CAfile certificate.pem

    - name: Upload signed installer
      uses: actions/upload-artifact@v2
      with:
        name: signed-installer
        path: your_installer_file.signed
