name: Test speciesnet env builder

on:
  workflow_dispatch:

jobs:
  test-env-sppnet:
    runs-on: windows-2022

    env:
      # remove if proven succesful after a release triggered job
      # RELEASE_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || inputs.tag_name }}
      # BUCKET_NAME: github-release-files-storage
      CONDA_DIR: C:\Miniconda
      BRANCH_NAME: ${{ github.event_name == 'release' && 'main' || github.ref_name }}


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release tag
        id: release_info
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}

      - name: Set latest release tag to global
        shell: cmd
        run: |
          set RELEASE_VERSION=${{ steps.release_info.outputs.release }}
          echo RELEASE_VERSION: %RELEASE_VERSION%
          echo RELEASE_VERSION=%RELEASE_VERSION%>> %GITHUB_ENV%

      - name: Set bucket name based on chosen branch
        shell: cmd
        run: |
          echo BRANCH_NAME is %BRANCH_NAME%
          if "%BRANCH_NAME%"=="main" (
              set "BUCKET_NAME=github-release-files-storage"
          ) else (
              set "BUCKET_NAME=github-release-files-storage-beta-versions"
          )
          echo BUCKET_NAME=%BUCKET_NAME%>> %GITHUB_ENV%
          echo BUCKET_NAME is "%BUCKET_NAME%"

      - name: check gsutil
        shell: cmd
        run: |
          gsutil --help
          where gsutil
